---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

<!-- README.md is generated from README.Rmd. Please edit that file -->


A series of meetups about the [reprex](https://reprex.tidyverse.org/)
package.

## Syllabus

The goal is to lean how to use the [reprex](https://reprex.tidyverse.org/)
package for effective and pleasant conversations about R code.

At the end of this series you will be able to do things like these:

* Prepare a reprex for different venues (e.g. GitHub and slack).
* Understand what makes a reprex good (do’s and don’ts).
* Create synthetic data with `dput()` and friends.

Each item in this syllabus corresponds to a meetup and a GitHub
[release](https://github.com/2DegreesInvesting/ds.docker/releases) that
preserves a snapshot of this repository exactly as it was shown during thee
meetup.

## Motivation and overview.

This meetup motivates the use of reprex and covers a fast-paced overview
of its most useful features.

Objectives:

* Understand why writing a good reprex is worth the effort.
* Overview the most useful features of reprex. 
* Learn where to find previous meetups on the topic.

## Next (tentative)

* Do's and don'ts.
* Synthetic data with `dput()` and friends.
* Lesser known features.

## Resources

* The [reprex](https://reprex.tidyverse.org) package.
